authors:
  john_doe:
    name: John Doe
    description: Full-stack developer and technical writer
    avatar: avatars/martin.png
    
  jane_smith:
    name: Jane Smith
    description: DevOps engineer and cloud architect
    avatar: avatars/christoph.png
    